# Generated by Django 5.2.5 on 2025-08-07 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('codigo', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='car.componente')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_problema', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('subcomponentes_sugeridos', models.JSONField(blank=True, null=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos', to='car.componente')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_repuestos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ganancia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_entrega', models.DateField()),
                ('diagnostico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcomponente', models.CharField(max_length=100)),
                ('accion', models.CharField(max_length=200)),
                ('tiempo_estimado_minutos', models.PositiveIntegerField()),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='RepuestoRecomendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_stock', 'En stock'), ('pedido', 'Solicitado'), ('instalado', 'Instalado')], default='pendiente', max_length=20)),
                ('reparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.reparacion')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('vin', models.CharField(blank=True, max_length=50, null=True)),
                ('placa', models.CharField(max_length=10)),
                ('descripcion_motor', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.vehiculo'),
        ),
        migrations.AddIndex(
            model_name='componente',
            index=models.Index(fields=['nombre'], name='car_compone_nombre_97a8e4_idx'),
        ),
        migrations.AddIndex(
            model_name='componente',
            index=models.Index(fields=['padre', 'nombre'], name='car_compone_padre_i_dd18c6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='componente',
            unique_together={('padre', 'nombre')},
        ),
    ]
