# Generated by Django 5.2.5 on 2025-08-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='componente',
            name='car_compone_nombre_97a8e4_idx',
        ),
        migrations.RemoveIndex(
            model_name='componente',
            name='car_compone_padre_i_dd18c6_idx',
        ),
        migrations.AlterUniqueTogether(
            name='componente',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='componente',
            name='codigo',
            field=models.CharField(default=1, editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='componente',
            index=models.Index(fields=['codigo'], name='car_compone_codigo_43a54b_idx'),
        ),
        migrations.AddConstraint(
            model_name='componente',
            constraint=models.UniqueConstraint(fields=('padre', 'nombre'), name='unique_nombre_por_padre'),
        ),
    ]
