# Generated by Django 5.2.5 on 2025-08-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_remove_componente_car_compone_nombre_97a8e4_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico',
            name='componente',
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='componentes',
            field=models.ManyToManyField(related_name='diagnosticos', to='car.componente'),
        ),
    ]
