# Generated by Django 5.2.5 on 2025-08-26 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_remove_diagnostico_componente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticoComponenteAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.accion')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.componente')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_componentes', to='car.diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='ComponenteAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.accion')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.componente')),
            ],
            options={
                'unique_together': {('componente', 'accion')},
            },
        ),
    ]
