# Generated by Django 5.2.5 on 2025-09-04 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_accion_diagnosticocomponenteaccion_componenteaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuestorecomendado',
            name='reparacion',
        ),
        migrations.DeleteModel(
            name='Presupuesto',
        ),
        migrations.DeleteModel(
            name='RepuestoRecomendado',
        ),
    ]
