# Generated by Django 5.2.5 on 2025-09-04 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_remove_repuestorecomendado_reparacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('oem', models.CharField(blank=True, max_length=64, null=True)),
                ('referencia', models.CharField(blank=True, max_length=128, null=True)),
                ('nombre', models.CharField(max_length=250)),
                ('marca', models.CharField(blank=True, max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('medida', models.CharField(blank=True, max_length=80)),
                ('posicion', models.CharField(blank=True, max_length=80)),
                ('unidad', models.CharField(default='pieza', max_length=20)),
                ('precio_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepuestoEnStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposito', models.CharField(default='bodega-principal', max_length=80)),
                ('proveedor', models.CharField(blank=True, max_length=120)),
                ('stock', models.IntegerField(default=0)),
                ('reservado', models.IntegerField(default=0)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='car.repuesto')),
            ],
            options={
                'unique_together': {('repuesto', 'deposito', 'proveedor')},
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reservado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='car.diagnostico')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car.repuesto')),
                ('repuesto_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.repuestoenstock')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'ingreso'), ('salida', 'salida'), ('reserva', 'reserva'), ('liberacion', 'liberacion')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('repuesto_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='car.repuestoenstock')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=120)),
                ('anio_desde', models.IntegerField()),
                ('anio_hasta', models.IntegerField()),
            ],
            options={
                'unique_together': {('marca', 'modelo', 'anio_desde', 'anio_hasta')},
            },
        ),
        migrations.CreateModel(
            name='ComponenteRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(blank=True, max_length=200)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.componente')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.repuesto')),
            ],
            options={
                'unique_together': {('componente', 'repuesto')},
            },
        ),
        migrations.CreateModel(
            name='RepuestoAplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(blank=True, max_length=80)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='car.repuesto')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.vehiculoversion')),
            ],
            options={
                'unique_together': {('repuesto', 'version')},
            },
        ),
    ]
