# Generated by Django 5.2.5 on 2025-09-11 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_repuesto_repuestoenstock_diagnosticorepuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='aceptado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='fecha_aceptacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('completado', 'Completado'), ('entregado', 'Entregado')], default='en_proceso', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('diagnostico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trabajo', to='car.diagnostico')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.accion')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.componente')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='car.trabajo')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car.repuesto')),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='car.trabajo')),
            ],
        ),
    ]
