# Generated by Django 5.2.5 on 2025-09-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_diagnostico_aceptado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
