# Generated by Django 5.2.5 on 2025-09-15 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_mecanico_trabajo_mecanicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='componentes',
            field=models.ManyToManyField(blank=True, related_name='trabajos', to='car.componente'),
        ),
        migrations.AddField(
            model_name='trabajoaccion',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trabajoaccion',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajorepuesto',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trabajorepuesto',
            name='componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.componente'),
        ),
        migrations.AddField(
            model_name='trabajorepuesto',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='estado',
            field=models.CharField(choices=[('iniciado', 'Iniciado'), ('trabajando', 'Trabajando'), ('completado', 'Completado'), ('entregado', 'Entregado')], default='en_proceso', max_length=20),
        ),
        migrations.CreateModel(
            name='TrabajoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='trabajos/fotos/%Y/%m/%d')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='car.trabajo')),
            ],
        ),
    ]
