# Generated by Django 5.2.5 on 2025-09-12 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_mecanico'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='mecanicos',
            field=models.ManyToManyField(blank=True, related_name='trabajos', to='car.mecanico'),
        ),
        migrations.AddField(
            model_name='trabajoaccion',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trabajoaccion',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajorepuesto',
            name='componente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car.componente'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TrabajoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='trabajos/fotos/%Y/%m/%d')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='car.trabajo')),
            ],
        ),
    ]
