# Generated by Django 5.2.5 on 2025-09-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_trabajo_mecanicos_trabajoaccion_completado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='estado',
            field=models.CharField(choices=[('iniciado', 'Iniciado'), ('trabajando', 'Trabajando'), ('completado', 'Completado'), ('entregado', 'Entregado')], default='en_proceso', max_length=20),
        ),
    ]
