# Generated by Django 5.2.5 on 2025-09-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_alter_trabajo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='componentes',
            field=models.ManyToManyField(blank=True, related_name='trabajos', to='car.componente'),
        ),
    ]
