# Generated by Django 5.2.5 on 2025-09-14 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_trabajo_componentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajorepuesto',
            name='componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.componente'),
        ),
    ]
