# Generated by Django 5.2.5 on 2025-09-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_alter_trabajorepuesto_componente'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajorepuesto',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trabajorepuesto',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
